name: Deploy

on:
  push:
    branches:
      - main
      - feat/github-actions
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ubuntu server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/whatsapp
            rm -rf *
            git clone https://github.com/pwkang/whatsapp-late-reply-detector builder
            cd builder
            npm install
            npm run build
            cp -r dist/* /home/whatsapp/public_html
      - name: write line
        run: |
          echo "Deployed at $(date)"